### ISSUE TITLE
Nothing should happen when user taps on “Send” button again on second request if user performed same action for another request earlier

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#142]
**Frequency:** 100%
**Repro on build version:** Test flight build V1.12.0(49) , Android Internal Build V1.12.0(1004294340)
 **Repro on devices:** Samsung Galaxy A5(7.0), iPhone XR (14.2),iPhone SE (13.4.1)
**Testing Account:**   (515) 444 0200 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)
**Pre-condition:** Users should have more than one request In-app notifications.
**Repro Steps:**
1. Launch the application & login with a test account.
2. Go to home screen & open “# Pending  requests” In-app CTA & tap on “View All” button.
3. Now tap on the “Send” button of the first request.
4. Now make sure that the continuous loading indicator should display instead of the Send button.
5. Now  tap on the Send button of another request before completing the loading indicator of the firstly tapped send button.
6. Observed that,
**Current Behavior:**  Continuous loading indicator displayed for second request also.
**Expected Behavior:**  Nothing should happen when the user taps on the Send button of the second request as first request sending amount is in process.
**Impact:** Bad user Experience.
**Investigation:** Also it is observed that, one by one Sending screens are displayed instead for last one when user taps on two Send buttons for different requests.
**Attachment:**  [NothingShouldHappenForSecondSendButton.mp4](https://drive.google.com/file/d/1YTz3Qk-C5fCdFdgJMyNmqDZ8xJemAhJI/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi I have verified this issue using  latest Android internal build V1.15.1 and Test Flight 1.15.1 & observed that issue is still reproduced.
**Verified On Devices:** iPhone SE (14.2), Samsung Galaxy A5(7.0)

**Comment by MuckT** [comment]
@ValoraQA can you please retest on v1.20.2 as this should be fixed by #985.

**Comment by ValoraQA** [comment]
Hey @MuckT We have verified this issue using latest Android internal build V1.20.2 and Test Flight 120.2  & observed that issue is still reproduced.
**Verified On Devices:** Redmi Note 8 (9.0), iPhone 6+ (12.4.5)
**Attachment:** [IssueStillRepro](https://drive.google.com/file/d/10C5LA95oNYS5b1Tx1ERikBTUr8kVRII4/view?usp=sharing)
