### ISSUE TITLE
 “Total Value” section not displayed on Home screen  when user update Valora application from previous build to latest build with logged in account

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1486]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.22.1
**Does Not Repro Version:** Test Flight Build V1.22.1
**Repro on devices:** One Plus 7T(11.0), Google Pixel 2XL (11.0), Samsung Galaxy F41  (11.0), Redmi note 8 (9.0)
**Does Not Repro on devices:** iPhone 12(15.0), iPhone SE (13.6.1), iPhone SE (14.2)
**Testing Account:** (680) 333 1978/[Recovery Phrase](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B11)

**Pre-condition:** Make sure that user account should have some balances

**Repro Steps:**
1. Launch the previous build (Play store build V1.21.0 here) & restore the account with the above credentials
2. Now observe balances from the Hamburger menu
3. Now update Valora application to the latest build (Android internal build V1.22.1 here)
4. Now redirect to the Home screen of an application
5. Observe that,

**Current Behavior:** “Total Value” section not displayed on Home screen & user not able to see the total sum of all balances on Home screen

**Expected Behavior:** User should be able to see the total sum of all balances in local currency with “Total value” section on the home screen 

**Investigation:** 
1. Also we have observed the same issue if we restore the account with no balances & then update the app to the latest version 
2. Also we have observed that user all balances displayed in Hamburger Menu instead of Home screen

**Impact:** Bad user experience as a user not able to see balances on Home screen after upgrading Valora application from previous to latest build

**Attachment:** [TotalValueSectionNotDisplayedAfterUpdating.mp4](https://drive.google.com/file/d/1BYty0fbFezLW2fxbrBdE-tLZORbBcC9r/view?usp=sharing)

**Comment by gnardini** [comment]
I think this is due to the remote config not loading immediately, it should fix itself after a while. I think while unfortunate it's not too big a deal. @ValoraQA can you confirm that after some time the "Total Value" section starts showing up?

**Comment by ValoraQA** [comment]
Hey, @gnardini We have re-verified this issue using Android internal build V1.22.1 & observed that issue is still reproduced

- [ ] We have verified by waiting more time after updating the Valora application to the latest build but still not able to see the "Total  Value" section on the Home screen
- [ ] Also we have tried with Kill & Relaunching the application after upgrading but facing the same issue

**Verified On Devices:** Redmi Note 8 (9.0), Samsung Galaxy F41  (11.0)
**Attachment:** [NotAbleToSeeAfterWaitingForLongTime](https://drive.google.com/file/d/120rl_ZMtf0FPPYe2QlGtBHDj2vO60QuX/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey, @jeanregisser We have a re-verified the issue using Android internal build V1.22.1 & observed that issue is still reproduced. Also, we have attached logs for the same.
**Verified On Device:** Redmi Note 8(9.0), Redmi Note 8(10.0), Samsung Galaxy F41 (11.0)
**Attachment:** [ NotAbleToSeeTotalValueStill](https://drive.google.com/file/d/1TNOAKgET2ljUoDJ-wdoaT-QCh_NNHx-x/view?usp=sharing)
**Logs:** [Celo_Logs](https://drive.google.com/file/d/1rUps8ZJ3eX9zd5QVpGLUMxc_OtaaCw8U/view?usp=sharing)
Thanks..!!

**Comment by ValoraQA** [comment]
Hey @MuckT , We have a re-verified the issue using Android internal build V1.22.1 & observed that issue is still reproduced.
Observation : "total balances" section is not seen after we update the build V:1.21.0 to V:1.22.1 
**Verified On Devices:** Redmi Note 8(9.0), OnePlus 7t(11.0)
Attachment: [update_issue.mp4](https://drive.google.com/file/d/1DN9OSHpliMJ0hPeQemyjYaJYbaCyscum/view?usp=sharing)
